## numpy 함수

In [ ]:
# %pip install numpy 해당 커널에 직접설치
import numpy as np
print(np.__version__)

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.9 MB 11.2 MB/s eta 0:00:01
   -------------- ------------------------- 4.7/12.9 MB 11.4 MB/s eta 0:00:01
   ---------------------- ----------------- 7.3/12.9 MB 11.6 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.9 MB 11.6 MB/s eta 0:00:01
   -------------------------------------- - 12.3/12.9 MB 11.7 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 10.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.
2.2.3


In [15]:
# Numpy 벡터화 연산과 비교하기 위한 list 예제
my_list = [1, 2, 3]
new_list = [x * 2 for x in my_list]  # 리스트 컴프리헨션 사용
print(new_list)

# 벡터화 연산 예시
my_array = np.array([1, 2, 3])
print(my_array)
new_array = my_array * 2  # 벡터화된 연산
print(new_array)

arr1 = np.arange(0, 10, 2) # arrage(start, stop, step)  0 <= x < 10
print(arr1)


arr2 = np.random.rand(4,5)
print(arr2)
arr2 = np.random.rand(2,4) # rand(2,4) 2개의 리스트 4개의 요소
print(arr2)
arr2 = np.random.rand(3,3)
print(arr2)

arr3 = arr2.reshape(1,9) # reshape(1,9) rand(3,3) 3개의 리스트 3개의 요소를 1개의 리스트 9개의 요소로
print(arr3)

npsum = np.sum([1,2,3]) # 리스트 내의 요소들의 합
print(npsum)

print(np.mean([1,2,3]))  # mean : 평균값

print(np.std([175,177,179,181,183])) # std : 표준편차

[2, 4, 6]
[1 2 3]
[2 4 6]
[0 2 4 6 8]
[[0.93743015 0.61166773 0.82350508 0.55423617 0.03465372]
 [0.56188681 0.71232292 0.89432829 0.57357776 0.42061875]
 [0.55069495 0.82422256 0.82563859 0.01666957 0.43127094]
 [0.01432698 0.54711828 0.21656535 0.69594767 0.90708591]]
[[0.28086668 0.23629123 0.05070089 0.14092015]
 [0.59051023 0.57512145 0.11536065 0.30051482]]
[[0.97845289 0.87282746 0.06482239]
 [0.67331031 0.01411482 0.38833595]
 [0.90781725 0.57768419 0.87894639]]
[[0.97845289 0.87282746 0.06482239 0.67331031 0.01411482 0.38833595
  0.90781725 0.57768419 0.87894639]]
6
2.0
2.8284271247461903


In [16]:
# 1부터 10까지의 숫자를 가진 배열 생성
data = np.arange(1, 11) # 1<=x<11
print(data)

# 합 계산
sum_data = np.sum(data)
print("합:", sum_data)

# 평균 계산
mean_data = np.mean(data)
print("평균:", mean_data)

# 표준편차 계산
std_data = np.std(data)
print("표준편차:", std_data)

[ 1  2  3  4  5  6  7  8  9 10]
합: 55
평균: 5.5
표준편차: 2.8722813232690143


In [ ]:
# 2차원 배열 생성
data = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
# 전체 요소의 합
sum_all = np.sum(data)
print("전체 요소의 합:", sum_all)

# 각 행의 합
row_sum = np.sum(data, axis=1) # axis=1 행끼리 / axis=0 열끼리 / 값을 주지 않으면 전체
print("각 행의 합:", row_sum)

# 각 열의 합
col_sum = np.sum(data, axis=0)
print("각 열의 합:", col_sum)

# 전체 요소의 평균
mean_all = np.mean(data)
print("전체 요소의 평균:", mean_all)

# 각 행의 평균
row_mean = np.mean(data, axis=1)
print("각 행의 평균:", row_mean)

# 각 열의 평균
col_mean = np.mean(data, axis=0)
print("각 열의 평균:", col_mean)

# 전체 요소의 표준편차
std_all = np.std(data)
print("전체 요소의 표준편차:", std_all)

# 각 행의 표준편차
row_std = np.std(data, axis=1)
print("각 행의 표준편차:", row_std)

# 각 열의 표준편차
col_std = np.std(data, axis=0)
print("각 열의 표준편차:", col_std)

전체 요소의 합: 45
각 행의 합: [ 6 15 24]
각 열의 합: [12 15 18]
전체 요소의 평균: 5.0
각 행의 평균: [2. 5. 8.]
각 열의 평균: [4. 5. 6.]
전체 요소의 표준편차: 2.581988897471611
각 행의 표준편차: [0.81649658 0.81649658 0.81649658]
각 열의 표준편차: [2.44948974 2.44948974 2.44948974]


In [ ]:
# 1차원 배열 생성
arr1 = np.array([1, 2, 3, 4, 5])
# 2차원 배열 생성
arr2 = np.array([[1, 2, 3],
                [4, 5, 6]])

# 배열의 shape 확인
print(arr2.shape)

# 특정 요소에 접근
print(arr2[1, 2])   # 두 번째 행, 세 번째 열
# 인덱스 접근은 0부터 시작!

# 슬라이싱
print(arr2[:, 1])  # 모든 행의 두 번째 열

# 특정 요소에 접근
print(arr2[0][1])  # 첫 번째 행의 두 번째 요소(특정 위치의 값을 가져올 때)

(2, 3)
6
[2 5]
2
